# Generated by Django 5.2.5 on 2025-08-24 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desafioadl", "0002_alter_tarea_eliminada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtarea",
            name="tarea_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtarea",
                to="desafioadl.tarea",
            ),
        ),
    ]
